server:
  port: 18080
vm:
 host: 192.168.19.10

spring:
  application:
    name: mybatis-plus-startBoot
  datasource:
    url: jdbc:mysql://${vm.host}:3306/mp_template?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# swagger
knife4j:
  enable: true
