server:
  port: 21000
xxl:
  job:
    admin:
      addresses: http://192.168.19.17:18081/xxl-job-admin
    accessToken:
    executor:
      appname: zyc-executor
      address: http://192.168.19.1:9999
      ip: 192.168.19.1
      port: 9999
      logpath: E:\logs\xxl-job\executor\job
      logretentiondays: 30
logging:
  config: classpath:logback.xml