server:
  port: 18200

shiro:
  sessionManager:
    sessionIdCookieEnabled: true        # 是否允许将sessionId 放到 cookie 中
    sessionIdUrlRewritingEnabled: true  # 是否允许将 sessionId 放到 Url 地址拦中
  unauthorizedUrl: /unauthorizedurl     # 访问未获授权的页面时，默认的跳转路径
  web:
    enabled: true     # 开启 shiro
  successUrl: /index  # 登录成功的跳转页面
  loginUrl: /login   # 登录页面